In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression

In [2]:
# Training Data
train_df_x = pd.read_csv('Training Data/Logistic_X_Train.csv')
train_df_y = pd.read_csv('Training Data/Logistic_Y_Train.csv')

# Test Data
test_df_x = pd.read_csv('Test Data/Logistic_X_Test.csv')

In [3]:
print(train_df_x.head())
print(train_df_y.head())

         f1        f2        f3
0 -1.239375  0.749101 -0.528515
1 -1.036070  0.801436 -1.283712
2 -0.615579  1.579521 -1.391927
3  1.335978  1.348651  1.433564
4  0.658925  1.300019  0.571603
   label
0      1
1      1
2      1
3      0
4      0


## Normalise Data

In [4]:
normaliser = preprocessing.MinMaxScaler()

# Normalising Train Data
train_x = normaliser.fit_transform(train_df_x)
print(train_x)

# Normalising Test Data
test_x = normaliser.fit_transform(test_df_x)
print(test_x)

[[0.30939437 0.56383919 0.46022638]
 [0.33758353 0.57048267 0.33420546]
 [0.39588669 0.66925402 0.31614735]
 ...
 [0.49347975 0.67677767 0.18236409]
 [0.69271003 0.57781964 0.79961378]
 [0.34538326 0.54033622 0.29153927]]
[[0.30186233 0.22054265 0.04342383]
 [0.22964129 0.51309438 0.43767095]
 [0.7120222  0.59564471 0.76700868]
 ...
 [0.23797065 0.42731313 0.36764754]
 [0.33768517 0.5808379  0.32878743]
 [0.50105531 0.36466791 0.58768674]]


In [5]:
train_y = train_df_y.values
train_y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [0],
       [1]])

## Classifier

In [6]:
classifier = LogisticRegression().fit(train_x, train_y)

/Users/ravikantsingh/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/ravikantsingh/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
outcomes = classifier.predict(test_x)
outcomes

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,

## Downloading Outcomes

In [8]:
outcome_df = pd.DataFrame({'lable' : outcomes})
outcome_df.to_csv('outcome.csv',index = False)